### ISSUE TITLE
Display not properly clearing with Python samples

### ISSUE THREAD

**Issue by marcelstoer** [waveshare/12.48inch-e-paper#1]
I was testing [epd_12in48_test.py](https://github.com/waveshare/12.48inch-e-paper/blob/master/RaspberryPi/python/examples/epd_12in48_test.py) and [Show_EN_Weather.py](https://github.com/waveshare/12.48inch-e-paper/blob/master/RaspberryPi/python/examples/Show_EN_Weather.py) on Raspberry Pi and found a major issue.

Both examples work flawlessly on a "quiet" empty display. However, after a while certain areas of the display wouldn't properly clear anymore. Running the examples repeatedly makes things worse rather than better. What normally helps is to let the display "cool down" for a while. Whether the pause has to be 10min, 30min or 60min I'm not sure anymore; didn't test yet. In any case at some point the examples start working again.

Please watch the video in the ZIP file for a demo of what's happening: [epd-not-clear.mp4.zip](https://github.com/waveshare/12.48inch-e-paper/files/4613685/BDMV.mp4.zip)

I also compared the code in this repository and the one you suggest to download at https://www.waveshare.com/wiki/12.48inch_e-Paper_Module_(B)#Download and found only minor differences.

P.S. I noticed the weather example has some commented `epd.clear()` at https://github.com/waveshare/12.48inch-e-paper/blob/master/RaspberryPi/python/examples/Show_EN_Weather.py#L65 but uncommenting makes no difference.

**Comment by marcelstoer** [comment]
The issue is caused by my mistake and a less then ideal PCB design in my opinion.

When the display arrived I 
- opened the back
- inserted both Raspberry Pi and ESP32 dev module
- connected a USB cable to each one _without powering them_
- closed the back

The plan was to experiment with Raspberry Pi first and then try ESP32. With both devices installed and connected I could just connect the USB cable of which ever device I want to work with.

However, turns out the appears to be a single shared VCC line on the PCB. Hence, if you power the Raspberry Pi you also power the ESP32! As I had the back of the display closed I didn't notice at first that the LED on both devices is ON even though I was only powering one via USB.

=> The PCB should have a separate VCC line for each device.
=> Once I removed the ESP32 everything works well with the Python samples

**Comment by martinberlin** [comment]
=> The PCB should have a separate VCC line for each device.

I also agree with this point. At least should be mentioned in the documentation that you are not supposed to connect the two at the same time :)
